# Generated by Django 4.0.5 on 2024-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_travel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='date',
            field=models.DateField(verbose_name='Check In Date'),
        ),
    ]
